name: CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (for action context only)
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            echo ">>> Pulling latest repo"
            cd ~/fxrates-service
            git fetch --all
            git reset --hard origin/main

            echo ">>> Building docker image"
            docker build -t fxrates:dev .

            echo ">>> Restarting services"

            docker compose -f ops/docker/docker-compose.yml -p fxrates-chan  --profile chan  up -d
            docker compose -f ops/docker/docker-compose.yml -p fxrates-db    --profile db    up -d
            docker compose -f ops/docker/docker-compose.yml -p fxrates-grpc  --profile grpc  up -d

            echo ">>> Done!"
          EOF